services:
  - type: web
    name: stockz-app
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: Stockz
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: AUTO_MIGRATE
        value: "true"
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
